### ISSUE TITLE
[BUG] Error with dff 0.6.4 and pyTelegramBotAPI 4.22.1 (Token Validation)

### ISSUE THREAD

**Issue by KurochkinVasiliy** [deeppavlov/chatsky#391]
**Describe the bug**
When using dff version 0.6.4 in combination with pyTelegramBotAPI version 4.22.1, the following error occurs:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\qramt\PycharmProjects\2024\qa-system-mvp\venv\lib\site-packages\dff\messengers\telegram\__init__.py", line 8, in <module>
    from .messenger import TelegramMessenger
  File "C:\Users\qramt\PycharmProjects\2024\qa-system-mvp\venv\lib\site-packages\dff\messengers\telegram\messenger.py", line 159, in <module>
    _default_messenger = TeleBot("")
  File "C:\Users\qramt\PycharmProjects\2024\qa-system-mvp\venv\lib\site-packages\telebot\__init__.py", line 196, in __init__
    util.validate_token(self.token)
  File "C:\Users\qramt\PycharmProjects\2024\qa-system-mvp\venv\lib\site-packages\telebot\util.py", line 694, in validate_token
    raise ValueError('Token must contain a colon')
ValueError: Token must contain a colon

This issue does not occur with earlier versions of pyTelegramBotAPI.

**To Reproduce**
pip install dff[telegram]==0.6.4 pyTelegramBotAPI==4.22.1
python -c "from dff.messengers.telegram import PollingTelegramInterface"

**Expected behavior**
The import of the PollingTelegramInterface from dff.messengers.telegram should not raise any errors.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version 3.9
 - dff version: 0.6.4
 - pyTelegramBotAPI version: 4.22.1

**Comment by RLKRo** [comment]
Fixed in 0.6.5 and 0.7.2.
